defaults:
  - _self_
  - dataset: bulk
  - model: esen/triforces
  - contrastive: default
  - loss: contrastive
  - trainer@train: default
  - logger: wandb

device: null

hydra:
  job:
    chdir: false
