_target_: triforces.models.triforces.TriForcesModel
interaction:
  _target_: triforces.models.triforces_struct.TriForcesStructBackbone
  embed_dim: 320
  num_layers: 4
  r_max: 6.0
  num_rbf: 64
  max_neighbors: 40
  max_atomic_number: ${max_atomic_number}
interaction_dim: ${.interaction.embed_dim}
interaction_name: esen
composition_dim: ${embed_dim}
structural_dim: ${embed_dim}
cutoff: ${.interaction.r_max}
max_neighbors: ${.interaction.max_neighbors}
num_elements: ${max_atomic_number}
