_target_: triforces.datasets.AugmentationDataset
return_pairs: true
n_augmentation_views: 2
n_opposite_views: 0
include_original: false
apply_augmentations_prob: 1.0
augmentations:
  noise:
    _target_: triforces.augmentations.CrystalNoiseAugmentation
    noise_scale: [0.0, 0.05]
augmentation_probabilities:
  noise: 1.0
