_target_: triforces.data.asedb_dataset.ASEDBDataset
path: null
repo_id: null
path_in_repo: null
revision: null
repo_type: dataset
token: null
cache_dir: null
local_dir: null
local_files_only: false
force_download: false
add_targets: []
extract_keys: []
keep_db_open: true
