_target_: triforces.data.atompack_dataset.AtompackDataset
path: null
repo_id: LeMaterial/Atompack
path_in_repo: mp_aloe
revision: null
repo_type: dataset
token: null
cache_dir: null
local_dir: null
local_files_only: false
force_download: false
use_mmap: false
add_targets: []
extract_keys: []
